# fly.toml app configuration file generated for deepfake-detection-backend on 2025-06-10T10:37:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'deepfake-detection-backend'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
